services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-strapi-x
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: strapi_user
      POSTGRES_PASSWORD: strapi_password
      POSTGRES_DB: strapi_db
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
      - ./docker/postgres-certs:/var/lib/postgresql/certs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U strapi_user -d strapi_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # minio:
  #   image: minio/minio:latest
  #   container_name: minio-strapi-x
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   environment:
  #     MINIO_ROOT_USER: user
  #     MINIO_ROOT_PASSWORD: password
  #   command: server /data --console-address ":9001"
  #   volumes:
  #     - ./docker/data:/data
  #     - ./docker/config:/root/.minio
